name: Destroy Jenkins EC2 Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Jenkins Server Infra
    runs-on: ubuntu-latest

    env:
      TF_VAR_db_password: ${{ secrets.RDS_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download PEM key from S3 (optional)
        run: |
          echo "Downloading PEM key if needed for destroy (optional)"
          aws s3 cp s3://jenkins-server-ec2/jenkinskey.pem jenkinskey.pem || true
          chmod 400 jenkinskey.pem || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -var-file=env_main/main.tfvars

      - name: Terraform Destroy (All Resources)
        run: terraform destroy -var-file=env_main/main.tfvars -auto-approve

      - name: Local PEM Cleanup
        if: always()
        run: rm -f jenkinskey.pem

      - name: Delete Existing EC2 Key Pair (optional cleanup)
        run: |
          echo "Deleting EC2 key pair 'jenkinskey' from AWS..."
          aws ec2 delete-key-pair \
            --key-name jenkinskey \
            --region us-east-1 || echo "Key pair might not exist or already deleted"

